### ISSUE TITLE
startDate does not work when multi-calendars is enabled

### ISSUE THREAD

**Issue by afonic** [Vuepic/vue-datepicker#259]
Thanks a lot for this excellent library!

**Describe the bug**
When using the startDate prop and multi-calendars is enabled the following errors is being thrown:
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'month')
    at P (vue-datepicker.js:839:16)
    at mt (vue-datepicker.js:991:7)
    at vue-datepicker.js:844:105
```

Removing multi-calendars fixes it.

**Desktop & mobile (please complete the following information):**
 - Browser Chrome 109
 - Library version 3.65

**Comment by afonic** [comment]
Thank you so much!
