### ISSUE TITLE
Input box click event does not result in a calender appearing on the DOM

### ISSUE THREAD

**Issue by sade-gray** [Vuepic/vue-datepicker#898]
**Describe the bug**
The outcome is that when you attempt to click on the input box, then nothing happens. As soon as the input box appears on the DOM, there is an error of this kind accompanied by a vue/core error

runtime-core.esm-bundler.js:47 
 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://github.com/vuejs/core 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'width')
    at vue-datepicker.js:3779:16
    at ReactiveEffect.fn (reactivity.esm-bundler.js:988:13)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at get value (reactivity.esm-bundler.js:1000:102)
    at Proxy.<anonymous> (vue-datepicker.js:3875:43)
    at renderComponentRoot (runtime-core.esm-bundler.js:887:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6020:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at instance.update (runtime-core.esm-bundler.js:6151:16)
    at setupRenderEffect (runtime-core.esm-bundler.js:6161:5)

Browser - Microsoft edge
latest version 8.7.0

**Comment by Jasenkoo** [comment]
There are a few reasons why this can happen, but without actual code, you have, nothing much to start here with.
